### ISSUE TITLE
PHPUnit error: Argument 3 passed to PHPUnit\TextUI\TestRunner::doRun() must be of the type bool, array given

### ISSUE THREAD

**Issue by nrutman** [php-actions/phpunit#10]
I wouldn't be surprised if this is a problem with how I've configured my action, but I keep getting the following error when PHPUnit attempts to run…
<img width="1052" alt="Screen Shot 2020-05-09 at 1 52 16 PM" src="https://user-images.githubusercontent.com/165184/81481212-5e69ce80-91fc-11ea-8d94-f5392fa44307.png">

Here's my workflow configuration:

```yaml
name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: php-actions/composer@v1
      - name: PHPUnit tests
        uses: php-actions/phpunit@v1
        with:
          config: phpunit.xml
          junit: junit.xml
```

Any suggestions on what I should be doing differently? Thanks!
