### ISSUE TITLE
bootstrap

### ISSUE THREAD

**Issue by Lewiscowles1986** [php-actions/phpunit#13]
> ##[warning]Unexpected input 'bootstrap', valid inputs are ['entryPoint', 'args', 'config', 'junit', 'memory']

```
Run php-actions/phpunit@v1
  with:
    config: phpunit.xml
    bootstrap: tests/bootstrap.php
    junit: test/phpunit/_junit/junit.xml
    memory: 512M
```
