### ISSUE TITLE
Php unit --coverage-text option

### ISSUE THREAD

**Issue by CorentinGuerrero** [php-actions/phpunit#16]
Hi, it's possible to launch test with --coverage-text option ?

**Comment by g105b** [comment]
Hi @CorentinGuerrero,

Yep, it's possible since the release of v8 and v9. Take a look at the actions.yml: 

https://github.com/php-actions/phpunit/blob/master/action.yml#L63-L65

You can pass any arguments you want into the `args` input.

Example file:

```yml
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v9
        with:
          args: --coverage-text
```

For coverage to work, you'll need to be running PHPUnit with XDebug installed. This isn't currently supported by this action, so may I ask if this is something you are planning to provide yourself (using a custom PHP runtime in some way), or do you want me to include XDebug by default in the PHPUnit action? I think the latter, but I'm just confirming with you to understand your use case better.
