### ISSUE TITLE
Passing environment variables to docker?

### ISSUE THREAD

**Issue by kx1s** [php-actions/phpunit#27]
How do I pass environment variables over to docker. I have github secrets that hold API keys. I have tried this but my php scripts fail since there is no environment variables set in docker.

```
 steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@master
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
            APIKEY: ${{ secrets.GO_APIKEY }}
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml
          args: --coverage-text
          php_version: 7.4
          version: 9.5.0
```
