### ISSUE TITLE
php 7.1 not available

### ISSUE THREAD

**Issue by Max84** [php-actions/phpunit#41]
Hi,

How can I use php 7.1?
I tested 7.4, 8.0, there is no problem. It can be useful to run phpunit with old php versions.

I got this error:

 ```
 Pulling docker.pkg.github.com/.../php-actions_phpunit_...:php-7.1-build2
  Error response from daemon: manifest for docker.pkg.github.com/...:php-7.1-build2 not found: manifest unknown: Docker image reference php-actions_phpunit_...:php-7.1-build2 not found under repo "..."
  Dockerfile:
  FROM php:7.1-cli-alpine
```

thanks for help

**Comment by g105b** [comment]
Hi @Max84 ,

Please can you provide your Github Actions yml configuration, so I can double check in a test repo? I've checked Docker Hub and 7.1 should still be available, so I'd like to create an example test case to explore this myself.

Thanks

**Comment by Max84** [comment]
Of course. Thanks.

```
name: TestsUnitaires

on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

jobs:

  TestsUnitaires:

    runs-on: ubuntu-latest

      - uses: actions/checkout@v3         

      - name: Tests unitaires
        uses: php-actions/phpunit@v3
        with:
            version: 5.7.19
            php_version: 7.1 
            configuration: .github/workflows/phpunit.xml
```
