### ISSUE TITLE
Dependabot bumps to older versions

### ISSUE THREAD

**Issue by cmbuckley-nhs** [php-actions/phpunit#49]
Because there are older releases with higher version numbers, Dependabot will try to bump this action incorrectly.

The workaround is to add the following [ignore condition](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore):

```yaml
ignore:
  - dependency-name: php-actions/phpunit
    versions: ["5", "6", "7", "8", "9"]
```

v5 and v6 don't have releases/tags, but Dependabot raised PRs for them today, so I've had to ignore those too.
