### ISSUE TITLE
Error: Locales is not getting picked in php-unit with php-actions.

### ISSUE THREAD

**Issue by ahmedkhan847** [php-actions/phpunit#53]
So I was moving to `php-actions/phpunit` since I am also using the composer package from you guys. But when I am running my GA with it my locales is not getting picked while running the tests. Although I am setting the locales during my build:

```
- name: Set Locales
        run: |
          sudo sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
          sudo sed -i -e 's/# de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/' /etc/locale.gen
          sudo sed -i -e 's/# nl_NL.UTF-8 UTF-8/nl_NL.UTF-8 UTF-8/' /etc/locale.gen
          sudo dpkg-reconfigure --frontend=noninteractive locales
```

But whenever I am running tests they are not getting picked. do I need to add some extension.

```
- name: PHPUnit Testing
        uses: php-actions/phpunit@v3
        with:
          version: 8.5.2
          php_version: "7.2"
          php_extensions: mongodb imagick soap bcmath gd exif json mysqli pcntl pdo_mysql zip pcov
          configuration: phpunit.xml.dist-workflow
          memory_limit: "1G"
          coverage_clover: coverage.xml
```

Any idea how can I fix it?
