### ISSUE TITLE
Need to whitelist `php_extensions` as it's giving a false positive warning message

### ISSUE THREAD

**Issue by summercms** [php-actions/phpunit#55]
This warning message seems to suggest there's an error in this repo

```
Warning: Unexpected input(s) 'php_extensions', valid inputs are ['entryPoint', 'args', 'configuration', 'log_junit', 'log_teamcity', 'testdox_html', 'testdox_text', 'testdox_xml', 'memory_limit', 'bootstrap', 'filter', 'testsuite', 'group', 'exclude_group', 'test_suffix', 'whitelist']
```

My code is:

```
      - name: "PHPUnit Tests"
        uses: "php-actions/phpunit@v9"
        with:
          php_extensions: "xdebug pcntl"
          bootstrap: "vendor/autoload.php"
          configuration: "phpunit.xml.dist"
          args: "--coverage-text"
          memory_limit: "256M"
        env:
          XDEBUG_MODE: "coverage"
          TEST_NAME: "Summer CMS"
```
