### ISSUE TITLE
PHP version 8.3 is not supported yet 

### ISSUE THREAD

**Issue by astronati** [php-actions/phpunit#58]

**Comment by g105b** [comment]
Hi, I'll look into this because it should automatically support all PHP versions that have been officially released on docker hub.

Leave it with me and I'll make sure 8.3 is up and running.

**Comment by g105b** [comment]
Hi, please see the example PHPUnit repository. I've added a workflow specifically targetting PHP 8.3:

https://github.com/php-actions/example-phpunit/actions/runs/7971809939/job/21762271183 here's the test passing

Here's the workflow file:

https://github.com/php-actions/example-phpunit/blob/c3497b9146c506b7b695a07af467f80cb116ba6e/.github/workflows/ci-latest.yml#L20

```yml
name: CI-latest

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        env:
          TEST_NAME: Scarlett
        with:
          version: 9.6
          php_version: 8.3
          bootstrap: vendor/autoload.php
          configuration: test/phpunit.xml
          args: --coverage-text
```
