### ISSUE TITLE
Code coverage is tricky to set up and references deprecated flags

### ISSUE THREAD

**Issue by shish** [php-actions/phpunit#59]
It would be nice if just specifying `coverage_*` automatically did whatever it needed, so I try that
```
    - uses: php-actions/phpunit@v3
      with:
        version: 10
        php_version: ${{ matrix.php }}
        php_extensions: xdebug
        coverage_text: true
        bootstrap: vendor/autoload.php
        args: tests
```

```
1) XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set
```

There are no instructions about how to set either of these flags, but by blind guessing I manage to figure it out:
```
    - uses: php-actions/phpunit@v3
      with:
        version: 10
        php_version: ${{ matrix.php }}
        php_extensions: xdebug
        coverage_text: true
        bootstrap: vendor/autoload.php
        args: tests
      env:
        XDEBUG_MODE: coverage
```

```
1) No filter is configured, code coverage will not be processed
```

Ok I need a filter -- The README mentions a `whitelist` parameter that seems to be what I want
```
    - uses: php-actions/phpunit@v3
      with:
        version: 10
        php_version: ${{ matrix.php }}
        php_extensions: xdebug
        coverage_text: true
        bootstrap: vendor/autoload.php
        whitelist: src
        args: tests
      env:
        XDEBUG_MODE: coverage
```

```
Unknown option "--whitelist"
```

Ok, looks like a few years ago `whitelist` was replaced with `coverage-filter`

```
    - uses: php-actions/phpunit@v3
      with:
        version: 10
        php_version: ${{ matrix.php }}
        php_extensions: xdebug
        coverage_text: true
        bootstrap: vendor/autoload.php
        coverage_filter: src
        args: tests
      env:
        XDEBUG_MODE: coverage
```

```
Warning: Unexpected input(s) 'coverage_filter', valid inputs are ['version', 'php_version', 'php_extensions', 'vendored_phpunit_path', 'configuration', 'log_junit', 'log_teamcity', 'testdox_html', 'testdox_text', 'memory_limit', 'bootstrap', 'filter', 'testsuite', 'group', 'exclude_group', 'test_suffix', 'whitelist', 'coverage_clover', 'coverage_cobertura', 'coverage_crap4j', 'coverage_html', 'coverage_php', 'coverage_text', 'coverage_xml', 'args']
```

Ok, so the action hasn't been updated to be compatible with the last few major releases, let's try `args`
```
    - uses: php-actions/phpunit@v3
      with:
        version: 10
        php_version: ${{ matrix.php }}
        php_extensions: xdebug
        coverage_text: true
        bootstrap: vendor/autoload.php
        args: --coverage-filter src tests
      env:
        XDEBUG_MODE: coverage
```

Success \o/

And now let's try using that coverage - The README mentions https://github.com/php-actions/code-coverage ... which is 404 ;(

**Comment by g105b** [comment]
Thank you for the issue report. I'll work on making this easier to set up and automating some of the steps.

**Comment by Seb33300** [comment]
Hello, any update on this? @shish did you manage to setup it? How to use the coverage?

**Comment by shish** [comment]
I switched to running phpunit from the command line, and never got coverage working D:

**Comment by g105b** [comment]
Here's a snippet from a working example project that I hope can help us all out here:

```yaml
  phpunit:
    runs-on: ubuntu-latest
    needs: [ composer ]
    strategy:
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]

    outputs:
      coverage: ${{ steps.store-coverage.outputs.coverage_text }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact-${{ matrix.php }}
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xvf /tmp/github-actions/build.tar ./

      - name: PHP Unit tests
        uses: php-actions/phpunit@v4
        env:
          XDEBUG_MODE: cover
        with:
          php_version: ${{ matrix.php }}
          php_extensions: xdebug
          coverage_text: _coverage/coverage.txt
          coverage_clover: _coverage/clover.xml

      - name: Store coverage data
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-${{ matrix.php }}-${{ github.run_number }}
          path: _coverage

  coverage:
    runs-on: ubuntu-latest
    needs: [ phpunit ]
    strategy:
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: code-coverage-${{ matrix.php }}-${{ github.run_number }}
          path: _coverage

      - name: Output coverage
        run: cat "_coverage/coverage.txt"

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
```

The snippet is lifted from [phpgt/dom's workflow yaml](https://github.com/PhpGt/Dom/blob/205cddcc82c002dfa48e874494efbf4c49497394/.github/workflows/ci.yml#L40-L94), [here's the job output](https://github.com/phpgt/Dom/actions/runs/14808816159/job/41580911984), and it uses [Codecov](https://app.codecov.io/gh/PhpGt/Dom) to visualise the coverage.
