### ISSUE TITLE
8.3 building failed

### ISSUE THREAD

**Issue by Buffele** [php-actions/phpunit#62]
My yml is as follows:

```yml
      - name: Run Tests
        uses: php-actions/phpunit@master
        with:
          version: "11.0.4"
          php_version: "8.3"
          php_extensions: "gd mysqli sockets"
          bootstrap: "app/autoload.php"
          configuration: "tests/phpunit.xml"
```

Getting the following error since today:

```
Run php-actions/phpunit@master
  with:
    version: 11.0.4
    php_version: 8.3
    php_extensions: gd mysqli sockets
    bootstrap: app/autoload.php
    configuration: tests/phpunit.xml
    test_suffix: Test.php,.phpt
Run set -e
Building PHP 8.3 with extensions: gd mysqli sockets ...
Error: Process completed with exit code 1.
```

Previously everything was running fine and I didn't touch anything regarding github actions, the .yml file or phpunit configuration or tests.

Any ideas?
