### ISSUE TITLE
process exit error

### ISSUE THREAD

**Issue by Buffele** [php-actions/phpunit#69]
My yml is as follows:

```yaml
      - name: Run Tests
        uses: php-actions/phpunit@master
        with:
          version: "11.2.8"
          php_version: "8.3"
          php_extensions: "gd mysqli sockets imagick ssh2"
          bootstrap: "app/autoload.php"
          configuration: "tests/phpunit.xml"
```

Getting the following error since today:

```
Run php-actions/phpunit@master
  with:
    version: 11.2.8
    php_version: 8.3
    php_extensions: gd mysqli sockets imagick ssh2
    bootstrap: app/autoload.php
    configuration: tests/phpunit.xml
Run set -e
Error: Process completed with exit code 1.
```

Previously everything was running fine and I didn't touch anything regarding github actions, the .yml file or phpunit configuration or tests.

Any ideas?
